[helpers]

[default]
depends = []

[default.files]
"bash.sh" = "~/.bashrc"
"ble.sh" = "~/.blerc"
"conda.yaml" = "~/.condarc"
"mise.toml" = "~/.config/mise/config.toml"
"starship.toml" = "~/.config/starship.toml"
"vim.vim" = "~/.vimrc"

[default.variables]

[settings]
default_target_type = "automatic"
