[helpers]

[default]
depends = []

[default.files]
"bash.sh" = "~/.bashrc"
"ble.sh" = "~/.blerc"
"conda.yaml" = "~/.condarc"
"fastfetch/fastfetch.jsonc" = "~/.config/fastfetch/config.jsonc"
"fastfetch/sakiko.txt" = "~/.local/share/fastfetch/sakiko.txt"
"mise.toml" = "~/.config/mise/config.toml"
"starship.toml" = "~/.config/starship.toml"
"vim.vim" = "~/.vimrc"
"zsh.sh" = "~/.zshrc"

[default.variables]

[settings]
default_target_type = "automatic"
