[helpers]

[settings]
default_target_type = "automatic"

[default]
depends = ["bash", "fastfetch", "git", "mise", "vscode"]

[default.files]
"conda.yaml" = "~/.condarc"
"starship.toml" = "~/.config/starship.toml"
"uv.toml" = "~/.config/uv/uv.toml"
"vim.vim" = "~/.vimrc"
"zsh.sh" = "~/.zshrc"

[default.variables]

[bash.files]
"bash/ibat.sh" = "~/.local/bin/ibat.sh"
"bash/ijq.sh" = "~/.local/bin/ijq.sh"
"bash/irg.sh" = "~/.local/bin/irg.sh"
"bash/isd.sh" = "~/.local/bin/isd.sh"

[fastfetch.files]
"fastfetch/fastfetch.jsonc" = "~/.config/fastfetch/config.jsonc"
"fastfetch/sakiko.txt" = "~/.local/share/fastfetch/sakiko.txt"

[git.files]
"git.ini" = "~/.gitconfig"

[git.variables]
git_name = ""
git_email = ""

[mise.files]
"mise/mise.toml" = "~/.config/mise/config.toml"
"mise/python-clis.txt" = "~/.default-python-packages"
"mise/javascript-clis.txt" = "~/.default-npm-packages"

[vscode.files]
"vscode/default/settings.jsonc" = "~/.config/Code/User/settings.json"
