includes = [".dotter/windows.toml"]
packages = ["default", "windows"]

[files]

[variables]
git_name = "Your git name"
git_email = "Your git email"

conda_root = "path/to/conda"
git_root = "path/to/git"
msys_root = "path/to/msys"
scoop_root = "path/to/scoop"
