includes = [".dotter/windows.toml"]
packages = ["default", "windows"]

[files]

[variables]
git_name = "Your git name"
git_email = "Your git email"
scoop_root = "path/to/scoop"
msys_root = "path/to/msys"
