[windows]
depends = ["scoop", "pwsh"]

[default.files]
"uv.toml" = "~/AppData/Roaming/uv/uv.toml"

[vscode.files]
"vscode/default/settings.jsonc" = "~/AppData/Roaming/Code/User/settings.json"

[pwsh.files]
"pwsh/pwsh.ps1" = "~/Documents/PowerShell/Microsoft.PowerShell_profile.ps1"

[windows.files]
"wt.json" = "~/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json"

[windows.variables]
conda_root = "~/miniforge3"
msys_root = "C:/msys64"
git_root = "C:/Program Files/Git"

[scoop.files]
"scoop/scoop.json" = "~/.config/scoop/config.json"

[scoop.variables]
scoop_root = "~/scoop"

