[windows]
depends = []

[default.files]
"uv.toml" = "~/AppData/Roaming/uv/uv.toml"

[windows.files]
"scoop.json" = "~/.config/scoop/config.json"
"pwsh.ps1" = "~/Documents/PowerShell/Microsoft.PowerShell_profile.ps1"

[windows.variables]
scoop_root = "~/scoop"
