[windows]
depends = []

[default.files]
"uv.toml" = "~/AppData/Roaming/uv/uv.toml"

[windows.files]
"pwsh.ps1" = "~/Documents/PowerShell/Microsoft.PowerShell_profile.ps1"
"scoop.json" = "~/.config/scoop/config.json"
"wt.json" = "~/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json"

[windows.variables]
scoop_root = "~/scoop"
msys_root = "C:/msys64"
